const DogBehaviours = [
  { label: "Protective", value: "Protective" },
  { label: "Aggressive", value: "Aggressive" },
  { label: "Shy", value: "Shy" },
  { label: "Friendly", value: "Friendly" },
  { label: "Independent", value: "Independent" },
  { label: "Affectionate", value: "Affectionate" },
  { label: "Playful", value: "Playful" },
  { label: "Calm", value: "Calm" },
  { label: "Curious", value: "Curious" },
  { label: "Fearful", value: "Fearful" },
  { label: "Confident", value: "Confident" },
  { label: "Stubborn", value: "Stubborn" },
  { label: "Energetic", value: "Energetic" },
  { label: "Passive", value: "Passive" },
  { label: "Dominant", value: "Dominant" },
  { label: "Submissive", value: "Submissive" },
  { label: "Intelligent", value: "Intelligent" },
  { label: "Loyal", value: "Loyal" },
  { label: "Territorial", value: "Territorial" },
  { label: "Anxious", value: "Anxious" },
  { label: "Social", value: "Social" },
  { label: "Responsive", value: "Responsive" },
  { label: "Sensitive", value: "Sensitive" },
  { label: "Distracted", value: "Distracted" },
  { label: "Determined", value: "Determined" },
  { label: "Patient", value: "Patient" },
  { label: "Impatient", value: "Impatient" },
  { label: "Adaptable", value: "Adaptable" },
  { label: "Excitable", value: "Excitable" },
  { label: "Alert", value: "Alert" },
  { label: "Proud", value: "Proud" },
  { label: "Gentle", value: "Gentle" },
  { label: "Timid", value: "Timid" },
  { label: "Hyperactive", value: "Hyperactive" },
  { label: "Sedentary", value: "Sedentary" },
  { label: "Mischevious", value: "Mischevious" },
  { label: "Nervous", value: "Nervous" },
  { label: "Destructive", value: "Destructive" },
  { label: "Cautious", value: "Cautious" },
  { label: "Needy", value: "Needy" },
  { label: "Perceptive", value: "Perceptive" },
  { label: "Obsessive", value: "Obsessive" },
  { label: "Hesitant", value: "Hesitant" },
];

export default DogBehaviours;
